import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { fetchFaq, fetchVideos } from './educationAPI';
import * as Models from '@/interfaces/videos-response'
import * as ModelsFaq from '@/interfaces/faq-response'

export interface EducationState {
    videos: Models.VideosResponse.IVideosResponse;
    faq: ModelsFaq.FaqResponse.IFaqResponse;
    status: 'idle' | 'loading' | 'failed';
    statusFaq: 'idle' | 'loading' | 'failed';
    errorMessage: string | null
}

const initialState: EducationState = {
    videos: {
        data: {
            videoList: [
                {
                    videoId: '',
                    videoCategory: {
                        videoCategoryId: '',
                        seqNo: 0,
                        categoryName: '',
                        categoryLocale: '',
                        categoryEnglish: '',
                        descriptionLocale: '',
                        descriptionEnglish: '',
                        slug: '',
                    },
                    titleSummary: '',
                    titleLocale: '',
                    titleEnglish: '',
                    descriptionLocale: '',
                    descriptionEnglish: '',
                    videoUrlLocale: '',
                    videoUrlEnglish: '',
                }
            ],
            categoryList: [
                {
                    videoCategoryId: '',
                    seqNo: 0,
                    categoryName: '',
                    categoryLocale: '',
                    categoryEnglish: '',
                    descriptionLocale: '',
                    descriptionEnglish: '',
                    slug: '',
                }
            ],
            totalRows: 0
        },
        errorCode: 0
    },
    faq: {
        data: {
            faqList: null,
            categoryList: null
        },
        errorCode: 0
    },
    statusFaq: 'idle',
    status: 'idle',
    errorMessage: ''
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchVideoAsync = createAsyncThunk(
    'education/fetchVideos',
    async () => {
        const response = await fetchVideos();
        // The value we return becomes the `fulfilled` action payload
        return response;
    }
);

export const fetchFaqAsync = createAsyncThunk(
    'education/fetchFaq',
    async () => {
        const response = await fetchFaq();
        // The value we return becomes the `fulfilled` action payload
        return response;
    }
);

export const educationSlice = createSlice({
    name: 'education',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchVideoAsync.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(fetchVideoAsync.fulfilled, (state, action) => {

                if (action.payload?.data || action.payload?.data !== null) {
                    state.status = 'idle';

                    let newData = { ...action.payload };
                    const newObject = {
                        videoCategoryId: 'all',
                        seqNo: 0,
                        categoryName: 'all',
                        categoryLocale: '-',
                        categoryEnglish: '-',
                        descriptionLocale: '-',
                        descriptionEnglish: '-',
                        slug: 'all',
                    };

                    newData.data?.categoryList?.unshift(newObject);
                    state.videos = action.payload;
                } else {
                    state.status = 'failed';
                    state.errorMessage = action.payload || 'Failed to fetch'
                }

            })
            .addCase(fetchVideoAsync.rejected, (state) => {
                state.status = 'failed';
            })
            .addCase(fetchFaqAsync.pending, (state) => {
                state.statusFaq = 'loading';
            })
            .addCase(fetchFaqAsync.fulfilled, (state, action) => {

                if (action.payload?.data || action.payload?.data !== null) {
                    state.statusFaq = 'idle';

                    state.faq = action.payload;
                } else {
                    state.statusFaq = 'failed';
                    state.errorMessage = action.payload || 'Failed to fetch'
                }

            })
            .addCase(fetchFaqAsync.rejected, (state) => {
                state.statusFaq = 'failed';
            });
    },
});

export const { } = educationSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectVideos = (state: RootState) => state.education.videos;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default educationSlice.reducer;
