import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { fetchNews } from './newsAPI';
import * as Models from '@/interfaces/news-response'

export interface AnnouncementState {
  news: Models.NewsResponse.INewsResponse;
  status: 'idle' | 'loading' | 'failed';
  errorMessage: string | null
}

const initialState: AnnouncementState = {
  news: {
    data: {
      postList: [
        {
          "postId": "",
          "postTitle": "",
          "description": "",
          "slug": "",
          "postCategoryIds": [],
          "postTagIds": [],
          "mediaPath": "",
          "seoTitle": null,
          "metaDescription": null,
          "publishDate": ""
        }
      ],
      categoryList: [
        {
          "categoryId": "",
          "categoryName": "",
          "slug": ""
        }
      ],
      totalRows: 0
    },
    errorCode: 0
  },
  status: 'idle',
  errorMessage: ''
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchNewsAsync = createAsyncThunk(
  'announcement/fetchNews',
  async () => {
    const response = await fetchNews();
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const announcementSlice = createSlice({
  name: 'announcement',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchNewsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchNewsAsync.fulfilled, (state, action) => {

        if (action.payload?.data || action.payload?.data !== null) {
          state.status = 'idle';
  
          let newData = { ...action.payload };
          const newObject = {
            "categoryId": "all",
            "categoryName": "All",
            "slug": "all"
          };
  
          newData.data?.categoryList?.unshift(newObject);
          state.news = action.payload;
        } else {
          state.status = 'failed';
          state.errorMessage = action.payload || 'Failed to fetch'
        }

      })
      .addCase(fetchNewsAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

export const { } = announcementSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectNews = (state: RootState) => state.announcement.news;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default announcementSlice.reducer;
